// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using strange.extensions.context.impl;

namespace strange.examples.strangerobots.game
{
	public class GameUtil
	{
		[Inject]
		public IGameModel gameModel{ get; set; }

		public Vector3 positionInWorldSpace(int x, int y) {
			float xPos = (y + .5f - (gameModel.currentLevel.height * .5f)) * gameModel.currentLevel.magnifier;
			float zPos = (x + .5f - (gameModel.currentLevel.width * .5f)) * gameModel.currentLevel.magnifier;
			return new Vector3 (xPos, 0f, zPos);
		}
	}
}

